Added inline buttons
ayrat555/el_monitorro pull request #261
Opened 2022-09-21 15:56 UTC by athulkrishnaaei

2022-09-22 06:15 UTC, pxp9 requested changes
Well done, just some comments. Keep the good work :)

2022-09-22 06:15 UTC, pxp9 commented on src/bot/handler.rs
> +                match update.content.clone() {
I think here you can not `clone` not sure, I am sure you don't need message or callback refs you can just match with variant and inside parentheses put this pattern `_`

2022-09-22 06:15 UTC, pxp9 commented on src/bot/handler.rs
> +        if command.starts_with("/list_subscriptions") {
Same as before , Command enum and match here please :)

2022-09-22 06:15 UTC, pxp9 commented on src/bot/handler.rs
> +        fn list_feed_id(db_connection: &mut PgConnection, message: &Message) -> String {
This should be returning a Result

2022-09-22 06:15 UTC, pxp9 commented on src/bot/handler.rs
> +pub fn get_feed_url_by_id(db_pool: Pool<ConnectionManager<PgConnection>>, data: i64) -> String {
Result please

2022-09-24 04:47 UTC, athulkrishnaaei commented on src/bot/commands/list_subscriptions_inline_keyboard/mod.rs
> +        let feed_id: i64 = feed.parse().unwrap();
if there is no subscriptions it will return a message you don't  have any subscriptions,so this inlinekeyboard generating function wont run

2022-09-24 04:48 UTC, athulkrishnaaei commented on src/bot/commands.rs
> +    fn list_subscriptions(&self, db_connection: &mut PgConnection, message: Message) -> String {
it returns a string you dont have any subscriptions if there is no subscriptions

2022-09-24 07:24 UTC, closed without merging