Added inline buttons
ayrat555/el_monitorro pull request #267
Opened 2022-09-24 16:20 UTC by athulkrishnaaei

Added inline buttons for setting template,global template,get filter,get template,unsubscribe,remove template etc

2022-09-25 05:02 UTC, ayrat555 reviewed
- Very good but has some room for improvement
- Let's use changes from the master branch
- Let's continue improving this pr (do not close and open again like you like to do)

2022-09-25 05:02 UTC, ayrat555 commented on src/http_client.rs
> -use crate::config::Config;
let's return this

2022-09-25 05:02 UTC, ayrat555 commented on src/sync/reader.rs
> +    let client = match Request::get(url)
let's use changes from the master branch

2022-09-25 05:02 UTC, ayrat555 commented on src/sync/sync_feed_job.rs
> +        let api = Api::default();
please revert

2022-09-26 09:52 UTC, athulkrishnaaei commented on src/bot/commands.rs
> +enum IncomingCommand {
right i have only made enum for the commands that show inline keyboards

2022-09-29 19:02 UTC, pxp9 requested changes
Keep the good work @athulkrishnaaei , just a few comments.

2022-09-29 19:02 UTC, pxp9 commented on src/bot/handler.rs
> +    fn process_callback_query(
Result here and manage unwraps with `?` operator please.

2022-09-30 07:05 UTC, athulkrishnaaei commented on src/bot/handler.rs
> +    fn parse_int_from_string(command: &str) -> Option<std::string::String> {
To filter out the feed id number from callback data

2022-09-30 07:16 UTC, athulkrishnaaei commented on src/bot/commands.rs
> +                api.send_message(&send_message_params).unwrap();
According to frankestien documentation https://github.com/ayrat555/frankenstein/blob/master/examples/inline_keyboard.rs
unwrap is used

2022-10-02 15:49 UTC, ayrat555 commented on src/bot/commands.rs
> +        match command {
this is very hacky way to intercept the command. let's modify `list_subscriptions` instead

2022-10-05 15:07 UTC, closed without merging

2022-10-05 15:14 UTC, ayrat555 commented
@athulkrishnaaei :crying_cat_face: